/* Governance glossary — so the platform stands alone. Every acronym and term of
   art an executive, auditor or engineer will hit on a governance surface, in
   plain language. Grouped by category; the surface filters and searches over it.

   Bilingual (Arabic + English): each entry carries `termAr`/`defAr`. The English
   term stays visible as the canonical reference (proper nouns / acronyms like
   EU AI Act, GPAI, FRIA), with the Arabic term alongside and the definition in
   the reader's language. Missing Arabic falls back to English at the call site. */

export const GLOSSARY = [
  // Regulatory
  { term: "EU AI Act", cat: "Regulatory", def: "The EU's binding, risk-tiered AI regulation. Bans some uses, imposes strict duties on high-risk systems, and lighter transparency duties elsewhere.", termAr: "قانون الذكاء الاصطناعي الأوروبي", defAr: "لائحة الاتحاد الأوروبي المُلزِمة والمتدرّجة بالمخاطر للذكاء الاصطناعي. تحظر بعض الاستخدامات، وتفرض واجبات صارمة على الأنظمة عالية الخطورة، وواجبات شفافية أخفّ فيما سواها." },
  { term: "High-risk AI", cat: "Regulatory", def: "AI whose use materially affects safety or fundamental rights (e.g. credit, employment). Carries the heaviest EU AI Act obligations (Annex III).", termAr: "الذكاء الاصطناعي عالي الخطورة", defAr: "ذكاء اصطناعي يؤثر استخدامه جوهرياً في السلامة أو الحقوق الأساسية (كالائتمان والتوظيف). يحمل أثقل التزامات القانون الأوروبي (الملحق الثالث)." },
  { term: "Prohibited practice", cat: "Regulatory", def: "A use the EU AI Act bans outright (Art. 5) — e.g. social scoring, emotion recognition at work. The answer is stop, not control.", termAr: "ممارسة محظورة", defAr: "استخدام يحظره القانون الأوروبي حظراً تاماً (المادة 5) — كالتقييم الاجتماعي والتعرّف على المشاعر في العمل. الجواب هو الإيقاف لا الضبط." },
  { term: "GPAI", cat: "Regulatory", def: "General-purpose AI model. Modifying one and sharing it beyond your team can make you a provider with Art. 53/55 duties.", termAr: "نموذج ذكاء اصطناعي عام الغرض", defAr: "نموذج ذكاء اصطناعي عام الغرض. تعديله ومشاركته خارج فريقك قد يجعلك مزوّداً تقع عليه واجبات المادتين 53/55." },
  { term: "Conformity assessment", cat: "Regulatory", def: "The formal check that a high-risk AI system meets EU AI Act requirements before it goes to market (Art. 43).", termAr: "تقييم المطابقة", defAr: "الفحص الرسمي لاستيفاء نظام ذكاء اصطناعي عالي الخطورة لمتطلبات القانون الأوروبي قبل طرحه في السوق (المادة 43)." },
  { term: "Post-market monitoring", cat: "Regulatory", def: "Ongoing monitoring of an AI system in production for new risks and drift (EU AI Act Art. 72).", termAr: "المراقبة بعد الطرح", defAr: "مراقبة مستمرة لنظام الذكاء الاصطناعي في الإنتاج بحثاً عن مخاطر جديدة وانحراف (القانون الأوروبي، المادة 72)." },
  { term: "GDPR Art. 22", cat: "Regulatory", def: "The right not to be subject to solely automated decisions with legal or similarly significant effects, absent safeguards.", termAr: "المادة 22 من GDPR", defAr: "الحق في عدم الخضوع لقرارات آلية بحتة ذات أثر قانوني أو مماثل في الأهمية، ما لم توجد ضمانات." },
  { term: "FRIA", cat: "Regulatory", def: "Fundamental Rights Impact Assessment — required for certain high-risk deployers under EU AI Act Art. 27.", termAr: "تقييم الأثر على الحقوق الأساسية", defAr: "تقييم الأثر على الحقوق الأساسية — مطلوب من بعض مشغّلي الأنظمة عالية الخطورة بموجب المادة 27." },
  // Standards
  { term: "ISO/IEC 42001", cat: "Standards", def: "The certifiable AI management-system standard. Structured like ISO 27001 (clauses 4–10 + Annex A controls).", termAr: "الأيزو 42001", defAr: "معيار نظام إدارة الذكاء الاصطناعي القابل للاعتماد. مُهيكَل كالأيزو 27001 (البنود 4–10 + ضوابط الملحق أ)." },
  { term: "ISO/IEC 27001", cat: "Standards", def: "The information-security management-system standard; the security backbone AI governance inherits from.", termAr: "الأيزو 27001", defAr: "معيار نظام إدارة أمن المعلومات؛ العمود الأمني الذي ترثه حوكمة الذكاء الاصطناعي." },
  { term: "NIST AI RMF", cat: "Standards", def: "The US voluntary AI Risk Management Framework, organised into four functions: Govern, Map, Measure, Manage.", termAr: "إطار NIST لإدارة مخاطر الذكاء الاصطناعي", defAr: "إطار أمريكي طوعي لإدارة مخاطر الذكاء الاصطناعي، منظّم في أربع وظائف: الحوكمة، والرسم، والقياس، والإدارة." },
  { term: "Statement of Applicability (SoA)", cat: "Standards", def: "The index listing every Annex A control, whether it applies, why, and the evidence — the first thing an ISO auditor reads.", termAr: "بيان قابلية التطبيق (SoA)", defAr: "الفهرس الذي يسرد كل ضابط في الملحق أ، وهل ينطبق ولماذا، والدليل — أول ما يقرأه مدقّق الأيزو." },
  { term: "Singapore Model AI Governance Framework", cat: "Standards", def: "Singapore's voluntary guidance on responsible AI: internal governance, human oversight, operations and stakeholder communication.", termAr: "إطار سنغافورة النموذجي لحوكمة الذكاء الاصطناعي", defAr: "إرشادات سنغافورة الطوعية للذكاء الاصطناعي المسؤول: الحوكمة الداخلية، والإشراف البشري، والعمليات، والتواصل مع أصحاب المصلحة." },
  { term: "OWASP LLM Top 10", cat: "Standards", def: "The community list of the top security risks specific to LLM applications (e.g. prompt injection, excessive agency).", termAr: "قائمة OWASP العشر لنماذج اللغة", defAr: "قائمة المجتمع لأبرز المخاطر الأمنية الخاصة بتطبيقات نماذج اللغة الكبيرة (كحقن الإدخالات والصلاحية المفرطة)." },
  { term: "MITRE ATLAS", cat: "Standards", def: "A knowledge base of adversarial tactics and techniques against AI/ML systems, modelled on MITRE ATT&CK.", termAr: "ميتري أطلس", defAr: "قاعدة معرفية للتكتيكات والتقنيات العدائية ضد أنظمة الذكاء الاصطناعي والتعلّم الآلي، على غرار ميتري ATT&CK." },
  // Technical
  { term: "Model drift", cat: "Technical", def: "When a model's behaviour degrades because the live data (or the underlying model) has shifted away from what it was validated on.", termAr: "انحراف النموذج", defAr: "تدهور سلوك النموذج لأن البيانات الحية (أو النموذج ذاته) ابتعدت عمّا جرى التحقق منه عليه." },
  { term: "Explainability", cat: "Technical", def: "The ability to give a human-understandable reason for a model's output — e.g. reason codes for an adverse decision.", termAr: "قابلية التفسير", defAr: "القدرة على تقديم سبب مفهوم للبشر لمُخرَج النموذج — كرموز أسباب قرار سلبي." },
  { term: "Bias / fairness testing", cat: "Technical", def: "Checking whether a model produces systematically different outcomes across protected groups.", termAr: "اختبار التحيّز / الإنصاف", defAr: "فحص ما إذا كان النموذج يُنتج نتائج مختلفة منهجياً عبر الفئات المحميّة." },
  { term: "HITL / HOTL", cat: "Technical", def: "Human-in-the-loop / human-on-the-loop — a person approves each action, or supervises and can intervene.", termAr: "الإنسان في الحلقة / على الحلقة", defAr: "الإنسان في الحلقة / على الحلقة — شخص يعتمد كل إجراء، أو يشرف ويمكنه التدخّل." },
  { term: "Prompt injection", cat: "Technical", def: "An attack that hides instructions in input to make an AI ignore its guardrails or leak data.", termAr: "حقن الإدخالات", defAr: "هجوم يُخفي تعليمات داخل الإدخال ليجعل الذكاء الاصطناعي يتجاهل حواجزه أو يسرّب بيانات." },
  { term: "RAG", cat: "Technical", def: "Retrieval-augmented generation — grounding a model's answer in retrieved enterprise documents rather than its training alone.", termAr: "التوليد المعزّز بالاسترجاع (RAG)", defAr: "التوليد المعزّز بالاسترجاع — إسناد إجابة النموذج إلى وثائق المؤسسة المُسترجعة بدلاً من تدريبه وحده." },
  { term: "Guardrail", cat: "Technical", def: "An automated control that blocks, masks or redacts unsafe input or output at the AI gateway boundary.", termAr: "حاجز الحماية", defAr: "ضابط آلي يحجب أو يُخفي أو يُنقّح المدخلات أو المخرجات غير الآمنة عند حدود بوابة الذكاء الاصطناعي." },
  { term: "Model card", cat: "Technical", def: "A standardised document describing a model's purpose, data, performance, limitations and governance.", termAr: "بطاقة النموذج", defAr: "وثيقة معيارية تصف غرض النموذج وبياناته وأداءه وحدوده وحوكمته." },
  // Governance
  { term: "Residual risk", cat: "Governance", def: "The risk that remains after controls are applied — scored likelihood × impact, tracked to appetite.", termAr: "الخطر المتبقي", defAr: "الخطر الباقي بعد تطبيق الضوابط — يُحتسب احتمالاً × أثراً، ويُتابَع مقابل حدّ التقبّل." },
  { term: "Least privilege", cat: "Governance", def: "Granting an agent or user only the capabilities they need; everything else is denied by default.", termAr: "الحد الأدنى من الصلاحيات", defAr: "منح الوكيل أو المستخدم القدرات التي يحتاجها فقط؛ وكل ما عداها مرفوض افتراضياً." },
  { term: "Capability-based access control", cat: "Governance", def: "Access defined per action an agent may take, not per role or model — enforced at call time.", termAr: "التحكّم في الوصول القائم على القدرات", defAr: "وصول محدَّد لكل إجراء يجوز للوكيل اتخاذه، لا حسب الدور أو النموذج — يُنفَّذ وقت الاستدعاء." },
  { term: "Evidence artifact", cat: "Governance", def: "The single document or record that proves a control is in place and satisfies its clause across frameworks.", termAr: "قطعة الدليل", defAr: "الوثيقة أو السجل الواحد الذي يُثبت قيام الضابط واستيفاءه لبنده عبر الأطر." },
  { term: "Convergence crosswalk", cat: "Governance", def: "A map of capabilities to the clause each satisfies in every framework at once — build one control, satisfy four.", termAr: "مصفوفة التقارب", defAr: "خريطة تربط القدرات بالبند الذي يستوفيه كلٌّ منها في كل إطار دفعة واحدة — ابنِ ضابطاً واحداً واستوفِ أربعة." },
  { term: "KRI", cat: "Governance", def: "Key Risk Indicator — a monitored metric with a threshold that signals rising risk before it becomes an incident.", termAr: "مؤشر المخاطر الرئيسي (KRI)", defAr: "مؤشر مخاطر رئيسي — مقياس مُراقَب بعتبة تُنذر بتصاعد الخطر قبل أن يصبح حادثاً." },
  { term: "Risk appetite", cat: "Governance", def: "The amount and type of risk an organisation is willing to accept in pursuit of its objectives.", termAr: "حدّ تقبّل المخاطر", defAr: "مقدار المخاطر ونوعها الذي تقبل المؤسسة تحمّله سعياً وراء أهدافها." },
  { term: "Statement of exception", cat: "Governance", def: "A time-boxed, approved deviation from a policy, with conditions and an owner — not a silent gap.", termAr: "بيان استثناء", defAr: "انحراف معتمد ومحدّد المدة عن سياسة، بشروط ومسؤول — لا فجوة صامتة." },
  // Roles
  { term: "CAIO", cat: "Roles", def: "Chief AI Officer — owns AI systems, lifecycle and model governance.", termAr: "مسؤول الذكاء الاصطناعي التنفيذي", defAr: "مسؤول الذكاء الاصطناعي التنفيذي — يملك أنظمة الذكاء الاصطناعي ودورة حياتها وحوكمة النماذج." },
  { term: "CGO", cat: "Roles", def: "Chief Governance Officer — chairs the converged forum; owns policy, risk tiering, exceptions and escalation.", termAr: "مسؤول الحوكمة التنفيذي", defAr: "مسؤول الحوكمة التنفيذي — يرأس المنتدى المُوحَّد؛ ويملك السياسة وتصنيف المخاطر والاستثناءات والتصعيد." },
  { term: "CDPO", cat: "Roles", def: "Chief Data Protection Officer — owns data lineage, DPIAs, retention and residency.", termAr: "مسؤول حماية البيانات التنفيذي", defAr: "مسؤول حماية البيانات التنفيذي — يملك تتبّع البيانات وتقييمات أثر الخصوصية والاحتفاظ والإقامة." },
  { term: "Model Risk", cat: "Roles", def: "The function that independently validates models and owns drift, performance and validation evidence.", termAr: "مخاطر النماذج", defAr: "الوظيفة التي تتحقّق من النماذج باستقلالية وتملك أدلة الانحراف والأداء والتحقق." },
  // ── Newly built this session ──
  { term: "Breach notification", cat: "Regulatory", def: "The duty to notify an authority (and sometimes affected people) of a personal-data breach within a fixed window — GDPR Art. 33 (72h), India DPDP, CERT-In (6h).", termAr: "الإبلاغ عن خرق البيانات", defAr: "واجب إبلاغ جهة تنظيمية (وأحياناً المتأثرين) بخرق بيانات شخصية خلال مدة محددة — GDPR المادة 33 (72 ساعة)، وDPDP الهندي، وCERT-In (6 ساعات)." },
  { term: "Serious incident", cat: "Regulatory", def: "A malfunction or event of a high-risk AI system that must be reported to the market-surveillance authority under EU AI Act Art. 73.", termAr: "حادث جسيم", defAr: "خلل أو حدث في نظام ذكاء اصطناعي عالي الخطورة يجب إبلاغه لجهة مراقبة السوق بموجب المادة 73 من القانون الأوروبي." },
  { term: "DPIA", cat: "Regulatory", def: "Data Protection Impact Assessment — the GDPR Art. 35 assessment of high-risk processing of personal data.", termAr: "تقييم أثر حماية البيانات (DPIA)", defAr: "تقييم أثر حماية البيانات — تقييم المادة 35 من GDPR لمعالجة البيانات الشخصية عالية الخطورة." },
  { term: "UAE PDPL", cat: "Regulatory", def: "The UAE Federal Personal Data Protection Law (Decree-Law 45/2021) — consent, data-subject rights, breach notification and cross-border transfer.", termAr: "قانون حماية البيانات الإماراتي (PDPL)", defAr: "قانون حماية البيانات الشخصية الاتحادي الإماراتي (المرسوم بقانون 45/2021) — الموافقة، وحقوق أصحاب البيانات، والإبلاغ عن الخرق، والنقل عبر الحدود." },
  { term: "DIFC / ADGM data laws", cat: "Regulatory", def: "The GDPR-aligned data-protection laws of the UAE financial free zones — DIFC (Law 5/2020) and ADGM (Regulations 2021).", termAr: "قوانين بيانات DIFC / ADGM", defAr: "قوانين حماية البيانات المتوافقة مع GDPR في المناطق المالية الحرة الإماراتية — DIFC (القانون 5/2020) وADGM (لوائح 2021)." },
  { term: "DESC", cat: "Regulatory", def: "Dubai Electronic Security Center — Dubai's information-security regulation and cloud policy, including data classification and residency.", termAr: "مركز دبي للأمن الإلكتروني (DESC)", defAr: "مركز دبي للأمن الإلكتروني — تنظيم أمن المعلومات وسياسة السحابة في دبي، بما في ذلك تصنيف البيانات وإقامتها." },
  { term: "Data provenance", cat: "Governance", def: "The governed record of where a system's training and grounding data came from — source lineage, lawful basis, IP clearance, PII class and a content hash.", termAr: "مصدر البيانات وحوكمتها", defAr: "السجل المُحوكَم لمصدر بيانات تدريب النظام وإسناده — تتبّع المصدر، والأساس القانوني، وإخلاء الملكية الفكرية، وتصنيف البيانات الشخصية، وبصمة محتوى." },
  { term: "Article 12 log", cat: "Governance", def: "The automatic, tamper-evident per-inference record EU AI Act Art. 12 requires over a system's lifetime.", termAr: "سجل المادة 12", defAr: "السجل الآلي المقاوم للعبث لكل استدلال، الذي تتطلبه المادة 12 من القانون الأوروبي طوال عمر النظام." },
  { term: "Tool-Call Ledger", cat: "Governance", def: "A hash-chained record of every tool call an agent attempted — what it was authorised to do vs what it did — where a tampered row breaks every later row.", termAr: "سجل استدعاء الأدوات", defAr: "سجل مُسلسَل بالتجزئة لكل استدعاء أداة حاوله وكيل — ما كان مُصرَّحاً به مقابل ما فعله — حيث يكسر أي صف مُعبَث به كل صف لاحق." },
  { term: "Capability token", cat: "Governance", def: "A short-lived, signed, per-tool-call grant scoped to exactly one tool for one agent — agents hold no standing keys.", termAr: "رمز القدرة", defAr: "منحة قصيرة الأجل موقّعة لكل استدعاء أداة، محصورة بأداة واحدة لوكيل واحد — لا يحمل الوكلاء مفاتيح دائمة." },
  { term: "Enforcement coverage", cat: "Governance", def: "The honest split of the AI estate into Enforced (inline gateway), Observed (out-of-band) and Shadow (detected only) — control reaches only the traffic on the plane.", termAr: "تغطية الإنفاذ", defAr: "التقسيم الأمين لمنشأة الذكاء الاصطناعي إلى: مُنفَّذ (بوابة داخل المسار)، ومُراقَب (خارج المسار)، وظِلّي (مُكتشَف فقط) — لا يبلغ الضبط إلا حركة المرور على المستوى." },
  { term: "AI-interaction disclosure", cat: "Governance", def: "The visible notice on every AI reply — which model, via the governed gateway, grounding, and logged to Article 12 — that makes transparency real.", termAr: "الإفصاح عن التفاعل مع الذكاء الاصطناعي", defAr: "الإشعار الظاهر على كل رد للذكاء الاصطناعي — أي نموذج، وعبر البوابة المُحوكَمة، والإسناد، ومُسجَّل في المادة 12 — الذي يجعل الشفافية واقعاً." },
  { term: "Egress control", cat: "Technical", def: "A deny-by-default policy over where an agent may send data or traffic — the enforcement point for data residency and exfiltration defence.", termAr: "ضبط الإخراج", defAr: "سياسة الرفض الافتراضي لوجهة إرسال الوكيل للبيانات أو حركة المرور — نقطة الإنفاذ لإقامة البيانات والدفاع ضد التسريب." },
  { term: "Circuit breaker", cat: "Technical", def: "Real-time revocation of an agent's capabilities when a threshold is breached — the adaptive half of human oversight.", termAr: "قاطع الدائرة", defAr: "إلغاء فوري لقدرات الوكيل عند تجاوز عتبة — النصف التكيّفي من الإشراف البشري." },
  { term: "MCP", cat: "Technical", def: "Model Context Protocol — the interface agents use to reach tools/servers; its registry pins signed, hashed manifests for supply-chain integrity.", termAr: "بروتوكول سياق النموذج (MCP)", defAr: "بروتوكول سياق النموذج — الواجهة التي يصل بها الوكلاء إلى الأدوات/الخوادم؛ ويُثبّت سجلّه بيانات وصف موقّعة ومُجزّأة لسلامة سلسلة التوريد." },
  { term: "Whole-life carbon", cat: "Governance", def: "An AI system's full-lifecycle footprint — training (amortised), inference, storage and retirement — disclosed as Scope 2 & 3 emissions (ISO/IEC TR 20226).", termAr: "الكربون طوال دورة الحياة", defAr: "البصمة الكاملة لنظام الذكاء الاصطناعي عبر دورة حياته — التدريب (مُوزّعاً)، والاستدلال، والتخزين، والإخراج من الخدمة — مُفصَحاً عنها كانبعاثات النطاقين 2 و3 (الأيزو TR 20226)." },
  // ── Added this session (Jurisdiction Atlas · UAE mapping · executive dashboards) ──
  { term: "Jurisdiction Atlas", cat: "Governance", def: "The multi-regime obligation map — which laws bind the enterprise where it operates, each self-flagging Applies / Monitor / Out of scope with effective dates and penalty exposure, all collapsing into one shared control set.", termAr: "أطلس الولايات القضائية", defAr: "خريطة الالتزامات متعددة الأنظمة — أيّ القوانين تُلزِم المؤسسة حيث تعمل، ويصنّف كلٌّ نفسه: ينطبق / مراقبة / خارج النطاق، بتواريخ سريان وتعرّض للعقوبات، منهارةً في مجموعة ضوابط واحدة مشتركة." },
  { term: "Data residency", cat: "Governance", def: "The requirement that certain data be stored and processed only within an approved geography — enforced at the egress boundary; central to UAE / Dubai (DESC) and EU cross-border transfer regimes.", termAr: "إقامة البيانات", defAr: "اشتراط تخزين ومعالجة بيانات بعينها ضمن نطاق جغرافي معتمد فقط — يُنفَّذ عند حدود الإخراج؛ ومحوري في نُظُم الإمارات / دبي (DESC) وأنظمة النقل الأوروبية عبر الحدود." },
  { term: "Computed posture", cat: "Governance", def: "A compliance score derived from the underlying control statuses (Met=100, Partial=60, Gap=0), never hand-asserted — so every headline number traces to real evidence.", termAr: "الوضعية المحسوبة", defAr: "درجة امتثال مُشتقّة من حالات الضوابط الأساسية (مُستوفى=100، جزئي=60، فجوة=0)، لا تُدّعى يدوياً — فيتتبّع كل رقم رئيسي دليلاً حقيقياً." },
  { term: "Time-to-value (TTV)", cat: "Governance", def: "The elapsed time from a program's kickoff to its first realized value — the executive metric for whether AI investment is converting, not merely being spent.", termAr: "زمن تحقّق القيمة (TTV)", defAr: "الزمن المنقضي من انطلاق البرنامج إلى أول قيمة مُحقّقة — المقياس التنفيذي لما إذا كان استثمار الذكاء الاصطناعي يتحوّل إلى قيمة لا مجرّد إنفاق." },
  { term: "Colorado AI Act (SB 205)", cat: "Regulatory", def: "Colorado's consumer-protection law imposing a duty of care on developers and deployers of high-risk AI to prevent algorithmic discrimination (effective 2026).", termAr: "قانون كولورادو للذكاء الاصطناعي (SB 205)", defAr: "قانون حماية المستهلك في كولورادو الذي يفرض واجب عناية على مطوّري ومشغّلي الذكاء الاصطناعي عالي الخطورة لمنع التمييز الخوارزمي (نافذ 2026)." },
  { term: "NYC Local Law 144", cat: "Regulatory", def: "New York City's law requiring an independent bias audit of automated employment decision tools before use, plus advance notice to candidates.", termAr: "قانون نيويورك المحلي 144", defAr: "قانون مدينة نيويورك الذي يوجب تدقيقاً مستقلاً للتحيّز على أدوات قرارات التوظيف الآلية قبل استخدامها، مع إشعار مسبق للمرشّحين." },
];

export const GLOSSARY_CATEGORIES = ["Regulatory", "Standards", "Technical", "Governance", "Roles"];

/* Arabic labels for the categories + chrome (English fallback at the call site). */
export const GLOSSARY_CAT_AR = {
  Regulatory: "تنظيمي", Standards: "المعايير", Technical: "تقني", Governance: "الحوكمة", Roles: "الأدوار", all: "الكل",
};
